name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f ./unitests/requirements.txt ]; then pip install -r ./unitests/requirements.txt; fi
      - name: Testing predict API
        run: |
          pytest ./unitests/api_predict.py
      - name: Testing shap API
        run: |
          pytest ./unitests/api_shap.py
      - name: Testing preprocess API
        run: |
          pytest ./unitests/api_preprocess.py


